// Generated by CoffeeScript 1.8.0
(function() {
  var nb, openNewTab, url;

  url = 'http://www.gestdown.info/api/sorties.php';

  nb = 5;

  openNewTab = function(tabUrl) {
    var win;
    win = window.open(tabUrl, '_blank');
    return win.focus();
  };

  $(function() {
    var imgur, releaseDiv;
    releaseDiv = $("#release");
    url += '?nb=' + nb;
    imgur = '//i.imgur.com/';
    return $.getJSON(url, function(data) {
      var a, div, elem, epInfo, episode, href, img, li, screen, screenPart, serie, title, ul, _i, _len, _results;
      ul = $("<ul>").appendTo(releaseDiv);
      _results = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        elem = data[_i];
        console.log(elem);
        episode = elem.episode;
        serie = elem.serie;
        screen = elem.screen;
        epInfo = serie + '<br />' + episode;
        title = serie + ' - ' + episode;
        href = "http://www.gestdown.info/ep-" + elem.id + ".html";
        screenPart = screen.split("?");
        screenPart = screenPart[0].split('/').pop();
        screenPart = screenPart.split(".");
        screen = imgur + screenPart[0] + 'm.' + screenPart[1];
        li = $("<li>").appendTo(ul);
        div = $('<div>').addClass('episodeInfo').html(epInfo).appendTo(li).click(function() {
          __gaTracker('send', 'event', 'sortie', href, title);
          return openNewTab(href);
        });
        img = $("<img>").attr({
          src: screen,
          alt: title,
          "class": 'sortie'
        });
        a = $('<a>').attr({
          href: href,
          target: '_blank'
        }).html(img).appendTo(li).click(function() {
          return __gaTracker('send', 'event', 'sortie', href, title);
        });
        _results.push(img);
      }
      return _results;
    });
  });

}).call(this);

//# sourceMappingURL=sortieLoader.js.map
